# -*- coding: utf-8 -*-
"""Cópia de Aula_04_Codelab - Desafios.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1If9K_4k-nrZPkyb1kJAz6caCfyP9vhH0

## **DESAFIO 01**

**Reajuste salarial**

As empresas @.com resolveram dar um aumento de salário aos seus colaboradores e lhe contrataram para desenvolver o programa que calculará os reajustes.

Faça um programa que recebe o salário de um colaborador e o reajuste segundo o seguinte critério, baseado no salário atual:
* salários até R$ 280,00 (incluindo) : aumento de 20%

* salários entre R\$ 280,00 e R$ 700,00 : aumento de 15%

* salários entre R\$ 700,00 e R$ 1500,00 : aumento de 10%

* salários de R$ 1500,00 em diante : aumento de 5% 

Após o aumento ser realizado, informe na tela:
* o salário antes do reajuste;

* o percentual de aumento aplicado;

* o valor do aumento;

* o novo salário, após o aumento."
"""

#Váriaveis de aumento e porcentagem.
increase = 0
range = 0 
#variáveis que guardam as porcentagem para cada faixa salárial.
range1 = 20
range2 = 15
range3 = 10
range4 = 5

salary = float(input('Qual salário atual ?\nR$').replace(",", "."))

if salary <= 280:
  range = range1 
  increase = (salary / 100)*range
elif salary > 280 or salary < 700:
  range = range2 
  increase = (salary / 100)*range
elif salary > 700 or salary < 1500:
  range = range3 
  increase = (salary / 100)*range
elif salary > 1500:
  range = range3 
  increase = (salary / 100)*range

print(f'Seu Salário antes do reajuste é: R${salary:.2f}')
print(f'Receberá um aumento de: {range}%')
print(f'R$:{increase:.2f} de aumento')
print(f'Você recebera R$:{increase+salary:.2f} de salário')

"""## **DESAFIO 02**

**Jogo da adivinhação**

Escreva um programa que faça o computador “pensar” em um número inteiro entre 0 e 10 e peça para o usuário tentar descobrir qual foi o número escolhido pelo computador. O programa deverá escrever na tela se o usuário venceu ou perdeu.
"""

import random 

result = random.randint(0,10)
user = int(input('O programa vai pensar em um número de 0 a 10\nTente adivinhar este número\nResposta: '))


while not result == user:
  print('Infelizmente você errou')
  user = int(input('Tente novamente\nResposta: '))
if result == user:
  print('Parabéns! Você acertou!')

"""## **Projeto da semana**

**Caixa eletrônico**

Faça um Programa para um caixa eletrônico. O programa deverá perguntar ao usuário a valor do saque e depois informar quantas notas de cada valor serão fornecidas. As notas disponíveis serão as de 1, 5, 10, 50 e 100 reais. O valor mínimo é de 10 reais e o máximo de 600 reais. O programa não deve se preocupar com a quantidade de notas existentes na máquina.

* Exemplo 1: Para sacar a quantia de 256 reais, o programa fornece duas notas de 100, uma nota de 50, uma nota de 5 e uma nota de 1;

* Exemplo 2: Para sacar a quantia de 399 reais, o programa fornece três notas de 100, uma nota de 50, quatro notas de 10, uma nota de 5 e quatro notas de 1.


"""

valor = int(input('Qual valor você deseja sacar? R$ '))

lobo = valor // 200
peixe = (valor % 200)//100
onca = ((valor%200)%100)//50
mico = (((valor%200)%100)%50)//20
arara = ((((valor%200)%100)%50)%20)//10
garça = (((((valor%200)%100)%50)%20)%10)//5
tartaruga = ((((((valor%200)%100)%50)%20)%10)%5)//2
beija_flor = (((((((valor%200)%100)%50)%20)%10)%5)%2)//1

if lobo != 0:
    print(f'Total de {lobo} cedulas de R$ 200,00')
if peixe != 0:
    print(f'Total de {peixe} cedulas de R$ 100,00')
if onca != 0:
    print(f'Total de {onca} cedulas de R$ 50,00')
if mico != 0:
    print(f'Total de {mico} cedulas de R$ 20,00')
if arara != 0:
    print(f'Total de {arara} cedulas de R$ 10,00')
if garça != 0:
    print(f'Total de {garça} cedulas de R$ 5,00')
if tartaruga != 0:
    print(f'Total de {tartaruga} cedulas de R$ 2,00')
if beija_flor != 0:
    print(f'Total de {beija_flor} cedulas de R$ 1,00')