# -*- coding: utf-8 -*-
"""Cópia de Aula_02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dgIDe81vOF5Ia4avoRaUWaEtPgY5_FfF

# Mini projetos

## #01 - Conversor de moedas

Crie um programa que solicite um um valor em real ao usuário e converta esse valor, para:

- DOLAR,
- EURO,
- LIBRA ESTERLINA,
- DÓLAR CANADENSE,
- PESO ARGENTINO,
- PESO CHILENO.

Para esse exercício você precisará realizar uma pesquisa para saber a cotação de cada moeda em real. Mostrar o resultado no formato $ XXXX.XX
"""

print('Olá Bluemer, imagine que você precisa viajar para outra nação mas não tem ideia de quanto vai ter na moeda local deste pais.')
print('vamos lá!')
print('primeiro diga-me quanto tem em R$(reais), lembre-se de usar ponto no lugar de virgula')
real = float(input('R$:').replace(',' , '.'))
#variáveis que guardam o valor das moedas 
dolar = real / 5.04
euro = real / 6.13
libra = real / 7.13
cad = real / 4.16
peso = real / 0.053
peso2 = real / 0.0070

print(f'Em dolares você teria: $ {dolar:.2f}' )
print(f'Em euros você teria: € {euro:.2f}' )
print(f'Em Libras esterlina você teria: GBP {libra:.2f}' )
print(f'Em dolares canadenses você teria: CAD {cad:.2f}')
print(f'Em peso argentinos você teria: ARS {peso:.2f}')
print(f'E em pesos chilenos você teria: CLP {peso2:.2f}')

"""## #02 - Calculadora de aumento de aluguel

Vamos construir um programa que irá calcular o aumento anual do seu aluguel.

A sua calculadora vai receber o `valor do aluguel` e calcular o aumento baseado no `IGPM de 31%`. A calculadora deve apresentar o aluguel reajustado no formato `R$ XXXX.XX`.
"""

print('Olá Bluemer, Gostaria de saber quanto será o aumento anual do seu alguel?')
rent = int(input('Quanto você paga de aluguel? :'))
IGPM = 31
adjusted = rent + rent * IGPM/100

print(f'você pagaria R$ {adjusted:.2f} de alguel')

