# -*- coding: utf-8 -*-
"""Cópia de exerciciosAula6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zrYcrQsfs1Yr7D_35TyuFpl7l7IJULdI
"""

#01 - Dado uma string com uma frase informada pelo usuário (incluindo espaços em branco), conte quantas vezes aparece as vogais a,e,i,o,u
frase = str(input('Digite uma frase:\n').upper().strip())
a = 0
e = 0
i = 0
o = 0
u = 0
for vogal in frase:
  if vogal == "A" or vogal == "Á" or vogal == 'Ã':
    a += 1
  if vogal == "E" or vogal == 'É' or vogal == 'Ê':
    e += 1
  if vogal == "I" or vogal == 'Í':
    i += 1
  if vogal == "O" or vogal == 'Ô' or vogal == 'Ó':
    o += 1
  if vogal == "U":
    u += 1
print('Sua frase tem:')
print(f'{a} letras A')
print(f'{e} letras E')
print(f'{i} letras I')
print(f'{o} letras O')
print(f'{u} letras U')

#02 - Desenvolva um código que pergunte um número n para o usuário e exiba todos seus divisores
num = int(input("Digite um número para saber seus divisores:\n"))
for i in range(1, num+1):
   if num % i == 0: 
     print(i)

###03 - Faça um script que o usuário escolha um número de início, um número de fim, e um número de
#passo. O programa deve printar todos os números do intervalo entre início e fim, "pulando" de
#acordo com o intervalo passado
begin = int(input('Digite um número para começar:\n'))
jump = int(input('Digite de quantos em quantos números\n'))
end = int(input("Digite o número que vai terminar:\n"))

for i in range(begin,end,jump):
  print(i)

#04 - Desenvolva um código em que o usuário vai entrar vários números e no final vai apresentar a soma deles (o usuário vai dizer quantos números serão informados antes de começar)
cont = 0

init = int(input('Digite a quantidade de números que deseja somar:\n'))
for i in range(init):
  cont =  cont + int(input('Digite o primeiro número:\n')) 
  
print(f'A soma entre esses números é :\n{cont}')

#05 - Faça um programa que mostre na tela uma contagem regressiva para o estouro de fogos de artifício, indo de 10 até 0, com uma pausa de 1 segundo entre eles.
cont = "10 9 8 7 6 5 4 3 2 1"
for i in cont: 
    print(i)

#06 - Escreva um programa onde o usuário digita uma frase e essa frase retorna sem nenhuma vogal

